### ISSUE TITLE
Write Requirements, Elicitation Questions and User Story

### ISSUE THREAD

**Issue by ilaydakurtboun** [dogukanarslan/SWE574-Group-3#25]

**Comment by ilaydakurtboun** [comment]
- [ ] Annotation Specifications and Elicitations @afize1 @emreberk92 
- [ ] Space Requirements Specifications @cansincomert 
- [ ] Badge Requirements Specifications @mirayiyidogan 
- [ ] Semantic Tag Requirements Specifications @ilaydakurtboun 
- [ ] User Roles and Permissions Specifications @Egelas 
- [ ] Recommendation Requirements Specifications @samedtorunn 
- [ ] Search Requirements Specifications @dogukanarslan

**Comment by afize1** [comment]
**Functional Requirements**

1. The system shall allow to add comments as annotation.
2. The system shall allow highlight selected parts of the post or post comment by user. The system shall enable to show when the comment as annotation is added, and by who.
3. The system shall enable to be answered comments by user.
4. The system shall enable to add comments as annotation which is linked to the highlighted parts of the post.
5. The system shall allow adding comments as links and text as annotation.
6. The system shall enable to show existing annotations.
7. The system shall enable to be removed highlighted parts or comments by owner of annotations.
8. The system shall enable to keep annotations.
9. The system shall enable to display kept annotations in the post page.

**Non-Functional Requirements**
1. The system shall meet w3c web annotation standards.

@emreberk92 please check requirements :)

**Comment by dogukanarslan** [comment]
**Search Requirements**
1. When a user searches a keyword without any additional selection, the system shall search for all spaces and posts.
2. The system shall separate search functionality by spaces, posts, or both.
3. When a user searches a keyword, the system shall list related results in a card view.
4. If search keywords include malicious scripts, the system shall prevent them from running on the server.
5. While a search request is pending, the system shall show a loading spinner until the request is resolved or rejected.
6. The system shall display the total count of search results.
7. When a user clicks on a search results card, the system shall redirect the user to the detail page.
8. The system shall search only posts or spaces that include selected labels.

**Comment by emreberk92** [comment]
Hello @afize1, thanks for adding the requirements regarding web annotation. I checked the requirements and have some questions as well as recommendations. I also added few more requirements, too. Please find them below and give your feedback :)

-2. The system shall allow highlight selected parts of the post or post comment by user. The system shall enable to show when the comment as annotation is added, and by who. --> **Do we really need to highlight the post comment by the user? I also propose to create an another requirement from the second sentence.**
-4. The system shall enable to add comments as annotation which is linked to the highlighted parts of the post. --> **What is the difference between this and first requirement? I think we can keep this one and remove the first one.**
-5. The system shall allow adding comments as links and text as annotation. --> **The difference with the req 4?**
-8. The system shall enable to keep annotations.
-9. The system shall enable to display kept annotations in the post page. --> **Do we need requirements 8 and 9? Because I think that first requirement already satisfies those.**
 
The requirements I add:
10. The system shall allow to share the annotation as well as the replies.
11. The system shall allow to add some tags below the comment.
12. The system shall show the date of the comments linked to annotation and display them from newest to oldest. 
13. The system shall show the username, who added the comment and replies under that.
14. The system shall allow to share the comment linked to annotation as public or private options. 
15. When a user clicks on the highlighted text, the system shall display annotations dedicated to text. 
16. Where user wants to see all comments, the system shall allow to show all annotations with a filtering option. 

> **Functional Requirements**
> 
> 1. The system shall allow to add comments as annotation.
> 2. The system shall allow highlight selected parts of the post or post comment by user.    The system shall enable to show when the comment as annotation is added, and by who.
> 3. The system shall enable to be answered comments by user.
> 4. The system shall enable to add comments as annotation which is linked to the highlighted parts of the post.
> 5. The system shall allow adding comments as links and text as annotation.
> 6. The system shall enable to show existing annotations.
> 7. The system shall enable to be removed highlighted parts or comments by owner of annotations.
> 8. The system shall enable to keep annotations.
> 9. The system shall enable to display kept annotations in the post page.
> 
> **Non-Functional Requirements**
> 
> 1. The system shall meet w3c web annotation standards.
> 
> @emreberk92 please check requirements :)

**Comment by mirayiyidogan** [comment]
Badge requirements specification has been made, need to overview

**Comment by ilaydakurtboun** [comment]
Semantic tag requirements has added to the [Requirements Wiki Page](https://github.com/dogukanarslan/SWE574-Group-3/wiki/Requirements-Specification)

**Comment by emreberk92** [comment]
Annotation requirements has been updated in [Requirements Wiki Page](https://github.com/dogukanarslan/SWE574-Group-3/wiki/Requirements-Specification#annotation-requirements).
