### ISSUE TITLE
Implement Semantic Tag

### ISSUE THREAD

**Issue by ilaydakurtboun** [dogukanarslan/SWE574-Group-3#31]
- [x] Create Add Tag Screen to Frontend @samedtorunn 
- [x] Investigate Wikidata Implementation @emreberk92 
- [x] Override Tag model according to Semantic Tag @cansincomert 
- [x] Improve Post and Tag relation @cansincomert

**Comment by emreberk92** [comment]
Wikidata implementation has been investigated, and related information has been added to the Wikipage: [Wikidata Implementation](https://github.com/dogukanarslan/SWE574-Group-3/wiki/Wikidata-Implementation). 

**Note**: The task was intentionally left open since using this feature as semantic tag is still being examined.

**Comment by uskudarli** [comment]
> Wikidata implementation has been investigated, and related information has been added to the Wikipage: [Wikidata Implementation](https://github.com/dogukanarslan/SWE574-Group-3/wiki/Wikidata-Implementation).
> 
> **Note**: The task was intentionally left open since using this feature as semantic tag is still being examined.

Wikipage: [Wikidata Implementation](https://github.com/dogukanarslan/SWE574-Group-3/wiki/Wikidata-Implementation)  doesn't exist

**Comment by emreberk92** [comment]
The content of the above link has been transferred to another title/link.

Please check the following link instead: [Wikidata Implementation for Semantic Tag Feature in Meet All
](https://github.com/dogukanarslan/SWE574-Group-3/wiki/Semantic-and-Non-Semantic-Tag-Use-in-Meet-All)
